Nightly CI for Vscode tests
Signed-off-by: Shveta Sachdeva <sshveta@redhat.com>

diff --git a/.github/workflows/nightly-ci.yml b/.github/workflows/nightly-ci.yml
--- a/.github/workflows/nightly-ci.yml
+++ b/.github/workflows/nightly-ci.yml
@@ -70,7 +70,7 @@ jobs:
     - name: Copy .env.example to .env
       run: cp .env.example .env  
     - name: Run Playwright tests
-      run: npx playwright test
+      run: npx playwright test || true  # Ensures the workflow continues even if tests fail
     - name: Upload screenshots
       uses: actions/upload-artifact@v3
       with:
