static paths for vscode, nodejs, and npm
Signed-off-by: midays <midays@redhat.com>

diff --git a/.github/workflows/windows-nightly-ci.yml b/.github/workflows/windows-nightly-ci.yml
--- a/.github/workflows/windows-nightly-ci.yml
+++ b/.github/workflows/windows-nightly-ci.yml
@@ -36,27 +36,44 @@ jobs:
         run: choco install nodejs -y
         shell: powershell
 
-      - name: Import Chocolatey Profile and Refresh Environment
+      - name: Define and Export Node.js and VSCode Paths
         shell: powershell
         run: |
-          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
-          refreshenv
+          # Define local variables for paths
+          $nodePath = 'C:\Program Files\nodejs'
+          $vscodePath = 'C:\Program Files\Microsoft VS Code\bin'
+          
+          # Check Node.js Path
+          if (-Not (Test-Path $nodePath)) {
+          Write-Error "Node.js installation path not found at: $nodePath"
+          exit 1
+          }
+          # Check VSCode Path
+          if (-Not (Test-Path $vscodePath)) {
+          Write-Error "VSCode installation path not found at: $vscodePath"
+          exit 1
+          }
+          
+          # Export the paths so they can be used in subsequent steps
+          "NODE_PATH=$nodePath" | Out-File -FilePath $env:GITHUB_ENV -Append
+          "VSCODE_PATH=$vscodePath" | Out-File -FilePath $env:GITHUB_ENV -Append
 
-      - name: Check Env PATH variable
-        shell: powershell
-        run: echo $env:PATH
-
-#      - name: Verify Installation
-#        run: |
-#          & "C:\Program Files\Microsoft VS Code\bin\code" --version
-#          & "C:\Program Files\nodejs\node.exe" --version
+#      - name: Check Env PATH variable
 #        shell: powershell
+#        run: echo $env:PATH
+
+      - name: Verify Installation
+        run: |
+          & "C:\Program Files\Microsoft VS Code\bin\code" --version
+          & "C:\Program Files\nodejs\node.exe" --version
+        shell: powershell
 
       - name: Verify VSCode and Node.js Installation
         shell: powershell
         run: |
-          code --version
-          node --version
+          # Use the exported paths
+          & "$env:VSCODE_PATH\code.exe" --version
+          & "$env:NODE_PATH\node.exe" --version
 
       - name: Clone kai-ci repo
         shell: powershell
@@ -69,7 +86,7 @@ jobs:
       - name: Install npm dependencies
         shell: powershell
         run: |
-          npm install .
+          & "$env:NODE_PATH\npm.cmd" install .
 
       - name: Run tests
         shell: powershell
